version: '3.8'

services:
  db:
    image: postgres:15
    container_name: manuastro_postgres
    restart: always
    environment:
      POSTGRES_USER: new_postgres_user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: manuastro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
